version: 1.0.{build}
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
build_script:
  - ps: ./build/package.ps1